{% set version = "0.16.0" %}

package:
  name: rasterstats
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/rasterstats/rasterstats-{{ version }}.tar.gz
  sha256: ad04711931fd8f02a5982115a2a03036c1420dfe31497a3d3de8e9d891f0357d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - affine <3.0
    - cligj >=0.4
    - fiona
    - numpy >=1.9
    - rasterio >=1.0
    - shapely
    - simplejson

test:
  imports:
    - rasterstats
  commands:
    - rio zonalstats --help
    - rio pointquery --help

about:
  home: https://github.com/perrygeo/python-raster-stats
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Summarize geospatial raster datasets based on vector geometries

extra:
  recipe-maintainers:
    - perrygeo
    - ocefpaf
