{% set version = "0.13.1" %}

package:
  name: rasterstats
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/rasterstats/rasterstats-{{ version }}.tar.gz
  sha256: 5600e58a80d9968a1afa8e25fc06e1e54cdfa7d078cb239db574b23167d0f0de

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python
    - pip
  run:
    - python
    - shapely
    - numpy >=1.9
    - rasterio >=0.27
    - cligj >=0.4
    - fiona
    - simplejson

test:
  files:
    - reference.py
  imports:
    - rasterstats
  commands:
    - rio zonalstats --help
    - rio pointquery --help

about:
  home: https://github.com/perrygeo/python-raster-stats
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: 'Summarize geospatial raster datasets based on vector geometries'

extra:
  recipe-maintainers:
    - perrygeo
    - ocefpaf
