{% set version = "0.15.0" %}

package:
  name: rasterstats
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/rasterstats/rasterstats-{{ version }}.tar.gz
  sha256: d554fbc7e749e5649dfcdbd7ea8e21c7388437bc66ef13fde9ef3662a258b277

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - shapely
    - numpy >=1.9
    - rasterio >=0.27
    - cligj >=0.4
    - fiona
    - simplejson

test:
  imports:
    - rasterstats
  commands:
    - rio zonalstats --help
    - rio pointquery --help

about:
  home: https://github.com/perrygeo/python-raster-stats
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Summarize geospatial raster datasets based on vector geometries

extra:
  recipe-maintainers:
    - perrygeo
    - ocefpaf
