{% set name = "rasterstats" %}
{% set version = "0.18.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rasterstats-{{ version }}.tar.gz
  sha256: 29389bfcbeac1a4206aba6e1d795058ec8a64d560efad48156c27fad97c2e09a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=61
    - pip
  run:
    - python >=3.7
    - affine <3.0
    - click >7.1
    - cligj >=0.4
    - fiona <1.9
    - numpy >=1.9
    - rasterio >=1.0
    - simplejson
    - shapely

test:
  imports:
    - rasterstats
  commands:
    - pip check
    - rio zonalstats --help
    - rio pointquery --help
  requires:
    - pip

about:
  home: https://github.com/perrygeo/python-raster-stats
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Summarize geospatial raster datasets based on vector geometries

extra:
  recipe-maintainers:
    - perrygeo
    - ocefpaf
