{% set name = "rasterstats" %}
{% set version = "0.20.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/rasterstats-{{ version }}.tar.gz
  sha256: 5b8ee775e815727767e0d359c03f3dd1c7840876d1d1d0c7a5a88ecf3e492938

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61
    - pip
  run:
    - python >={{ python_min }}
    - affine
    - click >7.1
    - cligj >=0.4
    - fiona
    - numpy >=1.9
    - rasterio >=1.0
    - simplejson
    - shapely

test:
  imports:
    - rasterstats
  commands:
    - pip check
    - rio zonalstats --help
    - rio pointquery --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/perrygeo/python-raster-stats
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Summarize geospatial raster datasets based on vector geometries

extra:
  recipe-maintainers:
    - perrygeo
    - ocefpaf
