travis:
  secure:
    BINSTAR_TOKEN: SRaprcPpOvT3kW8hfhj8ZV33Veo5rkDqxbgihA4U1hpwP+tyMAf6hjh+6EaE7M3ygJCDC9Vj6wr+TeBs5mRghu+TOtRgLujStqYhF+yssJe5j0zr1XCR2qrSd5Nj7shsFrnlRpyUSUdvbz1isS3ONZhTfK6ylBksVrGhhNFU1BcJ9BxCrV4tdx1KXxw0VramWIno6821lBgFeTp+h2/8kLjpPzpQp/kFiGBu2NLyJKVE6OCo30rILcH/saieeA6D8Xs/GLT6wRTkHF6lAXU0UIo912ph+S/kuFP6jyV6xHTedQXMtW42SzoLCbeYLmJAsI26d6iYYDDKa64E7Mj+RQ1yHTF582MZ+lMz/d1A2APUqG/7nbPitrPoyoaqnjYXt/Y0CGyKIMUWCw0urO/I0KiXOHXKdMhFaSZBTb1poID6bsvCMrt726kQta65os/FclYiXosAX52egrHsDSgU5ZSzodmxGMmRx3ST4EAzBEV4crj4xxubwNhkdOZbopTPOZkU/A0aoqa+gpH4ohtYgCA6XYCeDe00Mf7jx2b4iduBXfpqSOz8g1eHwIVreBaa0k/wttw9EimpCl+JXxWExGll9m494yPGuHVc10L3eUxEvciOfcx4CgbZSmxqya6Pu9Y5IaIF2wzIKdDsZKzr4Xj1nruDc0dWvT29KfXaXXI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
